<?php

namespace Database\Seeders;

use App\Models\Areas\Country;
use App\Models\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get languages
        $languages = Language::whereIn('code', ['en', 'ar'])->get()->keyBy('code');

        $countries = [
            ['code' => 'AF', 'phone_code' => '+93', 'active' => 1, 'name' => ['en' => 'Afghanistan', 'ar' => 'أفغانستان']],
            ['code' => 'AL', 'phone_code' => '+355', 'active' => 1, 'name' => ['en' => 'Albania', 'ar' => 'ألبانيا']],
            ['code' => 'DZ', 'phone_code' => '+213', 'active' => 1, 'name' => ['en' => 'Algeria', 'ar' => 'الجزائر']],
            ['code' => 'AS', 'phone_code' => '+1-684', 'active' => 1, 'name' => ['en' => 'American Samoa', 'ar' => 'ساموا الأمريكية']],
            ['code' => 'AD', 'phone_code' => '+376', 'active' => 1, 'name' => ['en' => 'Andorra', 'ar' => 'أندورا']],
            ['code' => 'AO', 'phone_code' => '+244', 'active' => 1, 'name' => ['en' => 'Angola', 'ar' => 'أنغولا']],
            ['code' => 'AI', 'phone_code' => '+1-264', 'active' => 1, 'name' => ['en' => 'Anguilla', 'ar' => 'أنغويلا']],
            ['code' => 'AG', 'phone_code' => '+1-268', 'active' => 1, 'name' => ['en' => 'Antigua and Barbuda', 'ar' => 'أنتيغوا وبربودا']],
            ['code' => 'AR', 'phone_code' => '+54', 'active' => 1, 'name' => ['en' => 'Argentina', 'ar' => 'الأرجنتين']],
            ['code' => 'AM', 'phone_code' => '+374', 'active' => 1, 'name' => ['en' => 'Armenia', 'ar' => 'أرمينيا']],
            ['code' => 'AW', 'phone_code' => '+297', 'active' => 1, 'name' => ['en' => 'Aruba', 'ar' => 'أروبا']],
            ['code' => 'AU', 'phone_code' => '+61', 'active' => 1, 'name' => ['en' => 'Australia', 'ar' => 'أستراليا']],
            ['code' => 'AT', 'phone_code' => '+43', 'active' => 1, 'name' => ['en' => 'Austria', 'ar' => 'النمسا']],
            ['code' => 'AZ', 'phone_code' => '+994', 'active' => 1, 'name' => ['en' => 'Azerbaijan', 'ar' => 'أذربيجان']],
            ['code' => 'BS', 'phone_code' => '+1-242', 'active' => 1, 'name' => ['en' => 'Bahamas', 'ar' => 'الباهاما']],
            ['code' => 'BH', 'phone_code' => '+973', 'active' => 1, 'name' => ['en' => 'Bahrain', 'ar' => 'البحرين']],
            ['code' => 'BD', 'phone_code' => '+880', 'active' => 1, 'name' => ['en' => 'Bangladesh', 'ar' => 'بنغلاديش']],
            ['code' => 'BB', 'phone_code' => '+1-246', 'active' => 1, 'name' => ['en' => 'Barbados', 'ar' => 'بربادوس']],
            ['code' => 'BY', 'phone_code' => '+375', 'active' => 1, 'name' => ['en' => 'Belarus', 'ar' => 'بيلاروسيا']],
            ['code' => 'BE', 'phone_code' => '+32', 'active' => 1, 'name' => ['en' => 'Belgium', 'ar' => 'بلجيكا']],
            ['code' => 'BZ', 'phone_code' => '+501', 'active' => 1, 'name' => ['en' => 'Belize', 'ar' => 'بليز']],
            ['code' => 'BJ', 'phone_code' => '+229', 'active' => 1, 'name' => ['en' => 'Benin', 'ar' => 'بنين']],
            ['code' => 'BM', 'phone_code' => '+1-441', 'active' => 1, 'name' => ['en' => 'Bermuda', 'ar' => 'برمودا']],
            ['code' => 'BT', 'phone_code' => '+975', 'active' => 1, 'name' => ['en' => 'Bhutan', 'ar' => 'بوتان']],
            ['code' => 'BO', 'phone_code' => '+591', 'active' => 1, 'name' => ['en' => 'Bolivia', 'ar' => 'بوليفيا']],
            ['code' => 'BA', 'phone_code' => '+387', 'active' => 1, 'name' => ['en' => 'Bosnia and Herzegovina', 'ar' => 'البوسنة والهرسك']],
            ['code' => 'BW', 'phone_code' => '+267', 'active' => 1, 'name' => ['en' => 'Botswana', 'ar' => 'بوتسوانا']],
            ['code' => 'BR', 'phone_code' => '+55', 'active' => 1, 'name' => ['en' => 'Brazil', 'ar' => 'البرازيل']],
            ['code' => 'BN', 'phone_code' => '+673', 'active' => 1, 'name' => ['en' => 'Brunei', 'ar' => 'بروناي']],
            ['code' => 'BG', 'phone_code' => '+359', 'active' => 1, 'name' => ['en' => 'Bulgaria', 'ar' => 'بلغاريا']],
            ['code' => 'BF', 'phone_code' => '+226', 'active' => 1, 'name' => ['en' => 'Burkina Faso', 'ar' => 'بوركينا فاسو']],
            ['code' => 'BI', 'phone_code' => '+257', 'active' => 1, 'name' => ['en' => 'Burundi', 'ar' => 'بوروندي']],
            ['code' => 'KH', 'phone_code' => '+855', 'active' => 1, 'name' => ['en' => 'Cambodia', 'ar' => 'كمبوديا']],
            ['code' => 'CM', 'phone_code' => '+237', 'active' => 1, 'name' => ['en' => 'Cameroon', 'ar' => 'الكاميرون']],
            ['code' => 'CA', 'phone_code' => '+1', 'active' => 1, 'name' => ['en' => 'Canada', 'ar' => 'كندا']],
            ['code' => 'CV', 'phone_code' => '+238', 'active' => 1, 'name' => ['en' => 'Cape Verde', 'ar' => 'الرأس الأخضر']],
            ['code' => 'KY', 'phone_code' => '+1-345', 'active' => 1, 'name' => ['en' => 'Cayman Islands', 'ar' => 'جزر كايمان']],
            ['code' => 'CF', 'phone_code' => '+236', 'active' => 1, 'name' => ['en' => 'Central African Republic', 'ar' => 'جمهورية أفريقيا الوسطى']],
            ['code' => 'TD', 'phone_code' => '+235', 'active' => 1, 'name' => ['en' => 'Chad', 'ar' => 'تشاد']],
            ['code' => 'CL', 'phone_code' => '+56', 'active' => 1, 'name' => ['en' => 'Chile', 'ar' => 'تشيلي']],
            ['code' => 'CN', 'phone_code' => '+86', 'active' => 1, 'name' => ['en' => 'China', 'ar' => 'الصين']],
            ['code' => 'CO', 'phone_code' => '+57', 'active' => 1, 'name' => ['en' => 'Colombia', 'ar' => 'كولومبيا']],
            ['code' => 'KM', 'phone_code' => '+269', 'active' => 1, 'name' => ['en' => 'Comoros', 'ar' => 'جزر القمر']],
            ['code' => 'CG', 'phone_code' => '+242', 'active' => 1, 'name' => ['en' => 'Congo', 'ar' => 'الكونغو']],
            ['code' => 'CD', 'phone_code' => '+243', 'active' => 1, 'name' => ['en' => 'Congo (DRC)', 'ar' => 'الكونغو الديمقراطية']],
            ['code' => 'CK', 'phone_code' => '+682', 'active' => 1, 'name' => ['en' => 'Cook Islands', 'ar' => 'جزر كوك']],
            ['code' => 'CR', 'phone_code' => '+506', 'active' => 1, 'name' => ['en' => 'Costa Rica', 'ar' => 'كوستاريكا']],
            ['code' => 'HR', 'phone_code' => '+385', 'active' => 1, 'name' => ['en' => 'Croatia', 'ar' => 'كرواتيا']],
            ['code' => 'CU', 'phone_code' => '+53', 'active' => 1, 'name' => ['en' => 'Cuba', 'ar' => 'كوبا']],
            ['code' => 'CY', 'phone_code' => '+357', 'active' => 1, 'name' => ['en' => 'Cyprus', 'ar' => 'قبرص']],
            ['code' => 'CZ', 'phone_code' => '+420', 'active' => 1, 'name' => ['en' => 'Czech Republic', 'ar' => 'التشيك']],
            ['code' => 'DK', 'phone_code' => '+45', 'active' => 1, 'name' => ['en' => 'Denmark', 'ar' => 'الدنمارك']],
            ['code' => 'DJ', 'phone_code' => '+253', 'active' => 1, 'name' => ['en' => 'Djibouti', 'ar' => 'جيبوتي']],
            ['code' => 'DM', 'phone_code' => '+1-767', 'active' => 1, 'name' => ['en' => 'Dominica', 'ar' => 'دومينيكا']],
            ['code' => 'DO', 'phone_code' => '+1-809', 'active' => 1, 'name' => ['en' => 'Dominican Republic', 'ar' => 'جمهورية الدومينيكان']],
            ['code' => 'EC', 'phone_code' => '+593', 'active' => 1, 'name' => ['en' => 'Ecuador', 'ar' => 'الإكوادور']],
            ['code' => 'EG', 'phone_code' => '+20', 'active' => 1, 'name' => ['en' => 'Egypt', 'ar' => 'مصر']],
            ['code' => 'SV', 'phone_code' => '+503', 'active' => 1, 'name' => ['en' => 'El Salvador', 'ar' => 'السلفادور']],
            ['code' => 'GQ', 'phone_code' => '+240', 'active' => 1, 'name' => ['en' => 'Equatorial Guinea', 'ar' => 'غينيا الاستوائية']],
            ['code' => 'ER', 'phone_code' => '+291', 'active' => 1, 'name' => ['en' => 'Eritrea', 'ar' => 'إريتريا']],
            ['code' => 'EE', 'phone_code' => '+372', 'active' => 1, 'name' => ['en' => 'Estonia', 'ar' => 'إستونيا']],
            ['code' => 'ET', 'phone_code' => '+251', 'active' => 1, 'name' => ['en' => 'Ethiopia', 'ar' => 'إثيوبيا']],
            ['code' => 'FJ', 'phone_code' => '+679', 'active' => 1, 'name' => ['en' => 'Fiji', 'ar' => 'فيجي']],
            ['code' => 'FI', 'phone_code' => '+358', 'active' => 1, 'name' => ['en' => 'Finland', 'ar' => 'فنلندا']],
            ['code' => 'FR', 'phone_code' => '+33', 'active' => 1, 'name' => ['en' => 'France', 'ar' => 'فرنسا']],
            ['code' => 'GA', 'phone_code' => '+241', 'active' => 1, 'name' => ['en' => 'Gabon', 'ar' => 'الغابون']],
            ['code' => 'GM', 'phone_code' => '+220', 'active' => 1, 'name' => ['en' => 'Gambia', 'ar' => 'غامبيا']],
            ['code' => 'GE', 'phone_code' => '+995', 'active' => 1, 'name' => ['en' => 'Georgia', 'ar' => 'جورجيا']],
            ['code' => 'DE', 'phone_code' => '+49', 'active' => 1, 'name' => ['en' => 'Germany', 'ar' => 'ألمانيا']],
            ['code' => 'GH', 'phone_code' => '+233', 'active' => 1, 'name' => ['en' => 'Ghana', 'ar' => 'غانا']],
            ['code' => 'GR', 'phone_code' => '+30', 'active' => 1, 'name' => ['en' => 'Greece', 'ar' => 'اليونان']],
            ['code' => 'GD', 'phone_code' => '+1-473', 'active' => 1, 'name' => ['en' => 'Grenada', 'ar' => 'غرينادا']],
            ['code' => 'GT', 'phone_code' => '+502', 'active' => 1, 'name' => ['en' => 'Guatemala', 'ar' => 'غواتيمالا']],
            ['code' => 'GN', 'phone_code' => '+224', 'active' => 1, 'name' => ['en' => 'Guinea', 'ar' => 'غينيا']],
            ['code' => 'GW', 'phone_code' => '+245', 'active' => 1, 'name' => ['en' => 'Guinea-Bissau', 'ar' => 'غينيا بيساو']],
            ['code' => 'GY', 'phone_code' => '+592', 'active' => 1, 'name' => ['en' => 'Guyana', 'ar' => 'غيانا']],
            ['code' => 'HT', 'phone_code' => '+509', 'active' => 1, 'name' => ['en' => 'Haiti', 'ar' => 'هايتي']],
            ['code' => 'HN', 'phone_code' => '+504', 'active' => 1, 'name' => ['en' => 'Honduras', 'ar' => 'هندوراس']],
            ['code' => 'HK', 'phone_code' => '+852', 'active' => 1, 'name' => ['en' => 'Hong Kong', 'ar' => 'هونغ كونغ']],
            ['code' => 'HU', 'phone_code' => '+36', 'active' => 1, 'name' => ['en' => 'Hungary', 'ar' => 'المجر']],
            ['code' => 'IS', 'phone_code' => '+354', 'active' => 1, 'name' => ['en' => 'Iceland', 'ar' => 'أيسلندا']],
            ['code' => 'IN', 'phone_code' => '+91', 'active' => 1, 'name' => ['en' => 'India', 'ar' => 'الهند']],
            ['code' => 'ID', 'phone_code' => '+62', 'active' => 1, 'name' => ['en' => 'Indonesia', 'ar' => 'إندونيسيا']],
            ['code' => 'IR', 'phone_code' => '+98', 'active' => 1, 'name' => ['en' => 'Iran', 'ar' => 'إيران']],
            ['code' => 'IQ', 'phone_code' => '+964', 'active' => 1, 'name' => ['en' => 'Iraq', 'ar' => 'العراق']],
            ['code' => 'IE', 'phone_code' => '+353', 'active' => 1, 'name' => ['en' => 'Ireland', 'ar' => 'أيرلندا']],
            ['code' => 'IL', 'phone_code' => '+972', 'active' => 1, 'name' => ['en' => 'Israel', 'ar' => 'إسرائيل']],
            ['code' => 'IT', 'phone_code' => '+39', 'active' => 1, 'name' => ['en' => 'Italy', 'ar' => 'إيطاليا']],
            ['code' => 'JM', 'phone_code' => '+1-876', 'active' => 1, 'name' => ['en' => 'Jamaica', 'ar' => 'جامايكا']],
            ['code' => 'JP', 'phone_code' => '+81', 'active' => 1, 'name' => ['en' => 'Japan', 'ar' => 'اليابان']],
            ['code' => 'JO', 'phone_code' => '+962', 'active' => 1, 'name' => ['en' => 'Jordan', 'ar' => 'الأردن']],
            ['code' => 'KZ', 'phone_code' => '+7', 'active' => 1, 'name' => ['en' => 'Kazakhstan', 'ar' => 'كازاخستان']],
            ['code' => 'KE', 'phone_code' => '+254', 'active' => 1, 'name' => ['en' => 'Kenya', 'ar' => 'كينيا']],
            ['code' => 'KI', 'phone_code' => '+686', 'active' => 1, 'name' => ['en' => 'Kiribati', 'ar' => 'كيريباتي']],
            ['code' => 'KP', 'phone_code' => '+850', 'active' => 1, 'name' => ['en' => 'North Korea', 'ar' => 'كوريا الشمالية']],
            ['code' => 'KR', 'phone_code' => '+82', 'active' => 1, 'name' => ['en' => 'South Korea', 'ar' => 'كوريا الجنوبية']],
            ['code' => 'KW', 'phone_code' => '+965', 'active' => 1, 'name' => ['en' => 'Kuwait', 'ar' => 'الكويت']],
            ['code' => 'KG', 'phone_code' => '+996', 'active' => 1, 'name' => ['en' => 'Kyrgyzstan', 'ar' => 'قيرغيزستان']],
            ['code' => 'LA', 'phone_code' => '+856', 'active' => 1, 'name' => ['en' => 'Laos', 'ar' => 'لاوس']],
            ['code' => 'LV', 'phone_code' => '+371', 'active' => 1, 'name' => ['en' => 'Latvia', 'ar' => 'لاتفيا']],
            ['code' => 'LB', 'phone_code' => '+961', 'active' => 1, 'name' => ['en' => 'Lebanon', 'ar' => 'لبنان']],
            ['code' => 'LS', 'phone_code' => '+266', 'active' => 1, 'name' => ['en' => 'Lesotho', 'ar' => 'ليسوتو']],
            ['code' => 'LR', 'phone_code' => '+231', 'active' => 1, 'name' => ['en' => 'Liberia', 'ar' => 'ليبيريا']],
            ['code' => 'LY', 'phone_code' => '+218', 'active' => 1, 'name' => ['en' => 'Libya', 'ar' => 'ليبيا']],
            ['code' => 'LI', 'phone_code' => '+423', 'active' => 1, 'name' => ['en' => 'Liechtenstein', 'ar' => 'ليختنشتاين']],
            ['code' => 'LT', 'phone_code' => '+370', 'active' => 1, 'name' => ['en' => 'Lithuania', 'ar' => 'ليتوانيا']],
            ['code' => 'LU', 'phone_code' => '+352', 'active' => 1, 'name' => ['en' => 'Luxembourg', 'ar' => 'لوكسمبورغ']],
            ['code' => 'MO', 'phone_code' => '+853', 'active' => 1, 'name' => ['en' => 'Macau', 'ar' => 'ماكاو']],
            ['code' => 'MK', 'phone_code' => '+389', 'active' => 1, 'name' => ['en' => 'North Macedonia', 'ar' => 'مقدونيا الشمالية']],
            ['code' => 'MG', 'phone_code' => '+261', 'active' => 1, 'name' => ['en' => 'Madagascar', 'ar' => 'مدغشقر']],
            ['code' => 'MW', 'phone_code' => '+265', 'active' => 1, 'name' => ['en' => 'Malawi', 'ar' => 'ملاوي']],
            ['code' => 'MY', 'phone_code' => '+60', 'active' => 1, 'name' => ['en' => 'Malaysia', 'ar' => 'ماليزيا']],
            ['code' => 'MV', 'phone_code' => '+960', 'active' => 1, 'name' => ['en' => 'Maldives', 'ar' => 'المالديف']],
            ['code' => 'ML', 'phone_code' => '+223', 'active' => 1, 'name' => ['en' => 'Mali', 'ar' => 'مالي']],
            ['code' => 'MT', 'phone_code' => '+356', 'active' => 1, 'name' => ['en' => 'Malta', 'ar' => 'مالطا']],
            ['code' => 'MH', 'phone_code' => '+692', 'active' => 1, 'name' => ['en' => 'Marshall Islands', 'ar' => 'جزر مارشال']],
            ['code' => 'MR', 'phone_code' => '+222', 'active' => 1, 'name' => ['en' => 'Mauritania', 'ar' => 'موريتانيا']],
            ['code' => 'MU', 'phone_code' => '+230', 'active' => 1, 'name' => ['en' => 'Mauritius', 'ar' => 'موريشيوس']],
            ['code' => 'MX', 'phone_code' => '+52', 'active' => 1, 'name' => ['en' => 'Mexico', 'ar' => 'المكسيك']],
            ['code' => 'FM', 'phone_code' => '+691', 'active' => 1, 'name' => ['en' => 'Micronesia', 'ar' => 'ميكرونيزيا']],
            ['code' => 'MD', 'phone_code' => '+373', 'active' => 1, 'name' => ['en' => 'Moldova', 'ar' => 'مولدوفا']],
            ['code' => 'MC', 'phone_code' => '+377', 'active' => 1, 'name' => ['en' => 'Monaco', 'ar' => 'موناكو']],
            ['code' => 'MN', 'phone_code' => '+976', 'active' => 1, 'name' => ['en' => 'Mongolia', 'ar' => 'منغوليا']],
            ['code' => 'ME', 'phone_code' => '+382', 'active' => 1, 'name' => ['en' => 'Montenegro', 'ar' => 'الجبل الأسود']],
            ['code' => 'MA', 'phone_code' => '+212', 'active' => 1, 'name' => ['en' => 'Morocco', 'ar' => 'المغرب']],
            ['code' => 'MZ', 'phone_code' => '+258', 'active' => 1, 'name' => ['en' => 'Mozambique', 'ar' => 'موزمبيق']],
            ['code' => 'MM', 'phone_code' => '+95', 'active' => 1, 'name' => ['en' => 'Myanmar', 'ar' => 'ميانمار']],
            ['code' => 'NA', 'phone_code' => '+264', 'active' => 1, 'name' => ['en' => 'Namibia', 'ar' => 'ناميبيا']],
            ['code' => 'NR', 'phone_code' => '+674', 'active' => 1, 'name' => ['en' => 'Nauru', 'ar' => 'ناورو']],
            ['code' => 'NP', 'phone_code' => '+977', 'active' => 1, 'name' => ['en' => 'Nepal', 'ar' => 'نيبال']],
            ['code' => 'NL', 'phone_code' => '+31', 'active' => 1, 'name' => ['en' => 'Netherlands', 'ar' => 'هولندا']],
            ['code' => 'NZ', 'phone_code' => '+64', 'active' => 1, 'name' => ['en' => 'New Zealand', 'ar' => 'نيوزيلندا']],
            ['code' => 'NI', 'phone_code' => '+505', 'active' => 1, 'name' => ['en' => 'Nicaragua', 'ar' => 'نيكاراغوا']],
            ['code' => 'NE', 'phone_code' => '+227', 'active' => 1, 'name' => ['en' => 'Niger', 'ar' => 'النيجر']],
            ['code' => 'NG', 'phone_code' => '+234', 'active' => 1, 'name' => ['en' => 'Nigeria', 'ar' => 'نيجيريا']],
            ['code' => 'NO', 'phone_code' => '+47', 'active' => 1, 'name' => ['en' => 'Norway', 'ar' => 'النرويج']],
            ['code' => 'OM', 'phone_code' => '+968', 'active' => 1, 'name' => ['en' => 'Oman', 'ar' => 'عمان']],
            ['code' => 'PK', 'phone_code' => '+92', 'active' => 1, 'name' => ['en' => 'Pakistan', 'ar' => 'باكستان']],
            ['code' => 'PW', 'phone_code' => '+680', 'active' => 1, 'name' => ['en' => 'Palau', 'ar' => 'بالاو']],
            ['code' => 'PS', 'phone_code' => '+970', 'active' => 1, 'name' => ['en' => 'Palestine', 'ar' => 'فلسطين']],
            ['code' => 'PA', 'phone_code' => '+507', 'active' => 1, 'name' => ['en' => 'Panama', 'ar' => 'بنما']],
            ['code' => 'PG', 'phone_code' => '+675', 'active' => 1, 'name' => ['en' => 'Papua New Guinea', 'ar' => 'بابوا غينيا الجديدة']],
            ['code' => 'PY', 'phone_code' => '+595', 'active' => 1, 'name' => ['en' => 'Paraguay', 'ar' => 'باراغواي']],
            ['code' => 'PE', 'phone_code' => '+51', 'active' => 1, 'name' => ['en' => 'Peru', 'ar' => 'بيرو']],
            ['code' => 'PH', 'phone_code' => '+63', 'active' => 1, 'name' => ['en' => 'Philippines', 'ar' => 'الفلبين']],
            ['code' => 'PL', 'phone_code' => '+48', 'active' => 1, 'name' => ['en' => 'Poland', 'ar' => 'بولندا']],
            ['code' => 'PT', 'phone_code' => '+351', 'active' => 1, 'name' => ['en' => 'Portugal', 'ar' => 'البرتغال']],
            ['code' => 'PR', 'phone_code' => '+1-787', 'active' => 1, 'name' => ['en' => 'Puerto Rico', 'ar' => 'بورتوريكو']],
            ['code' => 'QA', 'phone_code' => '+974', 'active' => 1, 'name' => ['en' => 'Qatar', 'ar' => 'قطر']],
            ['code' => 'RO', 'phone_code' => '+40', 'active' => 1, 'name' => ['en' => 'Romania', 'ar' => 'رومانيا']],
            ['code' => 'RU', 'phone_code' => '+7', 'active' => 1, 'name' => ['en' => 'Russia', 'ar' => 'روسيا']],
            ['code' => 'RW', 'phone_code' => '+250', 'active' => 1, 'name' => ['en' => 'Rwanda', 'ar' => 'رواندا']],
            ['code' => 'KN', 'phone_code' => '+1-869', 'active' => 1, 'name' => ['en' => 'Saint Kitts and Nevis', 'ar' => 'سانت كيتس ونيفيس']],
            ['code' => 'LC', 'phone_code' => '+1-758', 'active' => 1, 'name' => ['en' => 'Saint Lucia', 'ar' => 'سانت لوسيا']],
            ['code' => 'VC', 'phone_code' => '+1-784', 'active' => 1, 'name' => ['en' => 'Saint Vincent', 'ar' => 'سانت فنسنت']],
            ['code' => 'WS', 'phone_code' => '+685', 'active' => 1, 'name' => ['en' => 'Samoa', 'ar' => 'ساموا']],
            ['code' => 'SM', 'phone_code' => '+378', 'active' => 1, 'name' => ['en' => 'San Marino', 'ar' => 'سان مارينو']],
            ['code' => 'ST', 'phone_code' => '+239', 'active' => 1, 'name' => ['en' => 'Sao Tome and Principe', 'ar' => 'ساو تومي وبرينسيبي']],
            ['code' => 'SA', 'phone_code' => '+966', 'active' => 1, 'name' => ['en' => 'Saudi Arabia', 'ar' => 'السعودية']],
            ['code' => 'SN', 'phone_code' => '+221', 'active' => 1, 'name' => ['en' => 'Senegal', 'ar' => 'السنغال']],
            ['code' => 'RS', 'phone_code' => '+381', 'active' => 1, 'name' => ['en' => 'Serbia', 'ar' => 'صربيا']],
            ['code' => 'SC', 'phone_code' => '+248', 'active' => 1, 'name' => ['en' => 'Seychelles', 'ar' => 'سيشل']],
            ['code' => 'SL', 'phone_code' => '+232', 'active' => 1, 'name' => ['en' => 'Sierra Leone', 'ar' => 'سيراليون']],
            ['code' => 'SG', 'phone_code' => '+65', 'active' => 1, 'name' => ['en' => 'Singapore', 'ar' => 'سنغافورة']],
            ['code' => 'SK', 'phone_code' => '+421', 'active' => 1, 'name' => ['en' => 'Slovakia', 'ar' => 'سلوفاكيا']],
            ['code' => 'SI', 'phone_code' => '+386', 'active' => 1, 'name' => ['en' => 'Slovenia', 'ar' => 'سلوفينيا']],
            ['code' => 'SB', 'phone_code' => '+677', 'active' => 1, 'name' => ['en' => 'Solomon Islands', 'ar' => 'جزر سليمان']],
            ['code' => 'SO', 'phone_code' => '+252', 'active' => 1, 'name' => ['en' => 'Somalia', 'ar' => 'الصومال']],
            ['code' => 'ZA', 'phone_code' => '+27', 'active' => 1, 'name' => ['en' => 'South Africa', 'ar' => 'جنوب أفريقيا']],
            ['code' => 'SS', 'phone_code' => '+211', 'active' => 1, 'name' => ['en' => 'South Sudan', 'ar' => 'جنوب السودان']],
            ['code' => 'ES', 'phone_code' => '+34', 'active' => 1, 'name' => ['en' => 'Spain', 'ar' => 'إسبانيا']],
            ['code' => 'LK', 'phone_code' => '+94', 'active' => 1, 'name' => ['en' => 'Sri Lanka', 'ar' => 'سريلانكا']],
            ['code' => 'SD', 'phone_code' => '+249', 'active' => 1, 'name' => ['en' => 'Sudan', 'ar' => 'السودان']],
            ['code' => 'SR', 'phone_code' => '+597', 'active' => 1, 'name' => ['en' => 'Suriname', 'ar' => 'سورينام']],
            ['code' => 'SZ', 'phone_code' => '+268', 'active' => 1, 'name' => ['en' => 'Eswatini', 'ar' => 'إسواتيني']],
            ['code' => 'SE', 'phone_code' => '+46', 'active' => 1, 'name' => ['en' => 'Sweden', 'ar' => 'السويد']],
            ['code' => 'CH', 'phone_code' => '+41', 'active' => 1, 'name' => ['en' => 'Switzerland', 'ar' => 'سويسرا']],
            ['code' => 'SY', 'phone_code' => '+963', 'active' => 1, 'name' => ['en' => 'Syria', 'ar' => 'سوريا']],
            ['code' => 'TW', 'phone_code' => '+886', 'active' => 1, 'name' => ['en' => 'Taiwan', 'ar' => 'تايوان']],
            ['code' => 'TJ', 'phone_code' => '+992', 'active' => 1, 'name' => ['en' => 'Tajikistan', 'ar' => 'طاجيكستان']],
            ['code' => 'TZ', 'phone_code' => '+255', 'active' => 1, 'name' => ['en' => 'Tanzania', 'ar' => 'تنزانيا']],
            ['code' => 'TH', 'phone_code' => '+66', 'active' => 1, 'name' => ['en' => 'Thailand', 'ar' => 'تايلاند']],
            ['code' => 'TL', 'phone_code' => '+670', 'active' => 1, 'name' => ['en' => 'Timor-Leste', 'ar' => 'تيمور الشرقية']],
            ['code' => 'TG', 'phone_code' => '+228', 'active' => 1, 'name' => ['en' => 'Togo', 'ar' => 'توغو']],
            ['code' => 'TO', 'phone_code' => '+676', 'active' => 1, 'name' => ['en' => 'Tonga', 'ar' => 'تونغا']],
            ['code' => 'TT', 'phone_code' => '+1-868', 'active' => 1, 'name' => ['en' => 'Trinidad and Tobago', 'ar' => 'ترينيداد وتوباغو']],
            ['code' => 'TN', 'phone_code' => '+216', 'active' => 1, 'name' => ['en' => 'Tunisia', 'ar' => 'تونس']],
            ['code' => 'TR', 'phone_code' => '+90', 'active' => 1, 'name' => ['en' => 'Turkey', 'ar' => 'تركيا']],
            ['code' => 'TM', 'phone_code' => '+993', 'active' => 1, 'name' => ['en' => 'Turkmenistan', 'ar' => 'تركمانستان']],
            ['code' => 'TV', 'phone_code' => '+688', 'active' => 1, 'name' => ['en' => 'Tuvalu', 'ar' => 'توفالو']],
            ['code' => 'UG', 'phone_code' => '+256', 'active' => 1, 'name' => ['en' => 'Uganda', 'ar' => 'أوغندا']],
            ['code' => 'UA', 'phone_code' => '+380', 'active' => 1, 'name' => ['en' => 'Ukraine', 'ar' => 'أوكرانيا']],
            ['code' => 'AE', 'phone_code' => '+971', 'active' => 1, 'name' => ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة']],
            ['code' => 'GB', 'phone_code' => '+44', 'active' => 1, 'name' => ['en' => 'United Kingdom', 'ar' => 'المملكة المتحدة']],
            ['code' => 'US', 'phone_code' => '+1', 'active' => 1, 'name' => ['en' => 'United States', 'ar' => 'الولايات المتحدة']],
            ['code' => 'UY', 'phone_code' => '+598', 'active' => 1, 'name' => ['en' => 'Uruguay', 'ar' => 'أوروغواي']],
            ['code' => 'UZ', 'phone_code' => '+998', 'active' => 1, 'name' => ['en' => 'Uzbekistan', 'ar' => 'أوزبكستان']],
            ['code' => 'VU', 'phone_code' => '+678', 'active' => 1, 'name' => ['en' => 'Vanuatu', 'ar' => 'فانواتو']],
            ['code' => 'VA', 'phone_code' => '+379', 'active' => 1, 'name' => ['en' => 'Vatican City', 'ar' => 'الفاتيكان']],
            ['code' => 'VE', 'phone_code' => '+58', 'active' => 1, 'name' => ['en' => 'Venezuela', 'ar' => 'فنزويلا']],
            ['code' => 'VN', 'phone_code' => '+84', 'active' => 1, 'name' => ['en' => 'Vietnam', 'ar' => 'فيتنام']],
            ['code' => 'YE', 'phone_code' => '+967', 'active' => 1, 'name' => ['en' => 'Yemen', 'ar' => 'اليمن']],
            ['code' => 'ZM', 'phone_code' => '+260', 'active' => 1, 'name' => ['en' => 'Zambia', 'ar' => 'زامبيا']],
            ['code' => 'ZW', 'phone_code' => '+263', 'active' => 1, 'name' => ['en' => 'Zimbabwe', 'ar' => 'زيمبابوي']],
        ];

        foreach ($countries as $countryData) {
            $country = Country::updateOrCreate(
                ['code' => $countryData['code']],
                [
                    'code' => $countryData['code'],
                    'phone_code' => $countryData['phone_code'],
                    'active' => $countryData['active']
                ]
            );

            // Add translations
            if ($languages->isNotEmpty() && isset($countryData['name'])) {
                foreach ($countryData['name'] as $locale => $value) {
                    $country->setTranslation('name', $locale, $value);
                }
            }
        }
    }
}
